apiVersion: v2
name: kedify-agent
description: Kedify agent - Helm Chart
kubeVersion: ">=v1.23.0-0"
type: application
version: "v0.2.9"
appVersion: "v0.2.7"
icon: https://github.com/kedify/marketing/raw/refs/heads/main/public/assets/images/logo.svg
dependencies:
  - name: keda
    repository: https://kedify.github.io/charts
    version: v2.17.1-0
    condition: keda.enabled
  - name: keda-add-ons-http
    repository: https://kedify.github.io/charts
    version: v0.10.0-10
    condition: kedaAddOnsHttp.enabled,keda-add-ons-http.enabled
home: https://github.com/kedify/charts
sources:
  - https://github.com/kedify/agent
  - https://github.com/kedify/charts
