{{- if or .Values.interceptor.scaledObject.pendingRequestsTrigger.enabled .Values.interceptor.scaledObject.cpuTrigger.enabled .Values.interceptor.scaledObject.memoryTrigger.enabled }}
{{- if .Values.interceptor.scaledObject.waitForCrd }}
# minimal rbac for post-install jop that creates scaled object for interceptor
apiVersion: v1
kind: ServiceAccount
metadata:
  name: install-interceptor-so
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
    helm.sh/hook-weight: "-2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: install-interceptor-so
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
    helm.sh/hook-weight: "-2"
rules:
- apiGroups:
  - keda.sh
  resources:
  - scaledobjects
  verbs:
  - patch
  - create
  - get
  resourceNames:
  - {{ .Chart.Name }}-interceptor
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: install-interceptor-so
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
    helm.sh/hook-weight: "-2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: install-interceptor-so
subjects:
- kind: ServiceAccount
  name: install-interceptor-so
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
