{{- if .Values.agent.createApiKeySecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kedify-agent
  namespace: {{ .Release.Namespace }}
data:
  apikey: {{ b64enc .Values.agent.apiKey }}
  org_id: {{ b64enc .Values.agent.orgId }}
  {{- if .Values.agent.agentId }}
  agent_id: {{ b64enc .Values.agent.agentId }}
  {{- end }}
{{- end }}
