{{- if not .Values.agent.kedifyProxy.clusterWide }}
{{- $namespacesValues := keys .Values.agent.kedifyProxy.namespacedValues }}
{{- $namespacesEnvoyConfigs := keys .Values.agent.kedifyProxy.namespacedEnvoyConfigs }}
{{- $allNamespaces := concat $namespacesValues $namespacesEnvoyConfigs | sortAlpha | uniq }}
{{- range $ns := $allNamespaces }}
{{- $values := index $.Values.agent.kedifyProxy.namespacedValues $ns | default dict }}
{{- $envoyConfig := index $.Values.agent.kedifyProxy.namespacedEnvoyConfigs $ns | default dict }}
{{- $envoyConfigRoute := $envoyConfig.route | default dict }}
{{- $envoyConfigCluster := $envoyConfig.cluster | default dict }}
{{- $mergedValues := merge $values $.Values.agent.kedifyProxy.globalValues }}
{{- $mergedEnvoyConfigRoute := merge $envoyConfigRoute $.Values.agent.kedifyProxy.globalEnvoyConfigs.route }}
{{- $mergedEnvoyConfigCluster := merge $envoyConfigCluster $.Values.agent.kedifyProxy.globalEnvoyConfigs.cluster }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kedify-proxy-template-values
  namespace: {{ $ns | quote }}
  annotations:
    http.kedify.io/proxy: values
  labels:
    {{- include "kedify-agent.labels" $ | nindent 4 }}
data:
  content: |
    # this will override the defaults defined in https://github.com/kedify/charts/blob/main/kedify-proxy/values.yaml
    # this configmap holds the helm chart values for kedify proxy for namespace {{ $ns }} and will take precedence
    # over the global configmap in the keda namespace
{{- toYaml $mergedValues | nindent 4 }}
  envoy-config-route: |
    route:
{{- toYaml $mergedEnvoyConfigRoute | nindent 6 }}
  envoy-config-cluster: |
{{- toYaml $mergedEnvoyConfigCluster | nindent 4 }}
{{- end }}
{{- end }}
