apiVersion: install.kedify.io/v1alpha1
kind: KedifyConfiguration
metadata:
  name: kedify
  namespace: {{ .Release.Namespace }}
spec:
  clusterName: {{ .Values.clusterName }}
  {{- if .Values.agent.cloudAccountID }}
  cloudAccountID: "{{ .Values.agent.cloudAccountID }}"
  {{- end }}
  kedaInstallations:
  - name: {{ .Release.Namespace }}
    namespace: {{ .Release.Namespace }}
    {{- if .Values.agent.features.multitenantKEDAEnabled }}
    multitenancy: {}
    {{- end }}
{{ toYaml .Values.agent.kedifyConfiguration | indent 4 }}
