{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kedify-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kedify-proxy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kedify-proxy.selectorLabels" . | nindent 6 }}
  {{- with .Values.podDisruptionBudget.spec }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end -}}
