{{- if .Values.autoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.autoscaling.scaledObjectName | default (include "kedify-proxy.fullname" .) }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    name: "kedify-proxy"
  triggers:
    - type: cpu
      metadata:
        value: "75"
      metricType: Utilization
    - type: memory
      metadata:
        value: "90"
      metricType: Utilization
  minReplicaCount: {{ .Values.autoscaling.minReplicaCount }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicaCount }}
  advanced:
  {{- with .Values.autoscaling.horizontalPodAutoscalerConfig }}
    horizontalPodAutoscalerConfig:
    {{- toYaml . | nindent 6 }}
  {{- end }}
{{- end }}
