{
 "title": "Kedify / Predictor",
 "description": "Operational overview for Kedify Predictor and its models.",
 "tags": [
  "kedify",
  "keda",
  "autoscaling"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "description": "Health of Kedify Predictor.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kedify_agent_component_up{name=\"predictorAddon\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kedify_predictor_runtime_info", "legendFormat": "{{db}}" }
   ]
  },
  {
   "title": "Total Models",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kedify_predictor_metricpredictor_status{status=\"success\"}) or vector(0)",
     "legendFormat": "active scalers"
    }
   ]
  },
  {
   "title": "Total Model Retrains",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kedify_predictor_model_retrains) or vector(0)",
     "legendFormat": "scaled objects"
    }
   ]
  },
  {
   "title": "Total Points Written",
   "type": "stat",
   "description": "When using KEDA's existing scaler as a source, how many metric data points has been sent over gRPC to predictor",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kedify_predictor_metric_points_written) or vector(0)",
     "legendFormat": "paused scaled objects"
    }
   ]
  },
  {
   "title": "Paused MPs",
   "type": "stat",
   "description": "How many MetricPredictor resources are being paused",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_kedify_metricpredictor_paused) or vector(0)",
     "legendFormat": "paused scaled objects"
    }
   ]
  },
  {
   "title": "Operations by Model",
   "type": "table",
   "description": "Per model aggregated operation counts (how many times certain APIs were called)",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "kedify_predictor_model_operation_count",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "MP conditions by name",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 4 },
   "targets": [
    {
     "expr": "label_join(kube_kedify_metricpredictor_status_condition, \"join_key\", \"/\", \"namespace\", \"metricpredictor\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 14 },
   "options": {
    "content": "# Predictor REST Api\n\n```bash\nkubectl port-forward -nkeda svc/kedify-predictor 8000\n```\n\nSome selected endpoints:\n- http://localhost:8000 (Scagger docs w/ all the REST endpoints)\n- http://localhost:8000/redoc (ReDoc docs)\n- http://localhost:8000/models (List all models)\n- http://localhost:8000/models/mm-in-ten (Get model info for 'mm-in-ten' model)\n- http://localhost:8000/models/mm-in-ten/graph (Matplotlib graph of trained predictive model)\n- http://localhost:8000/models/mm-in-ten/graphComponents (Predictive model decomposed to its seasonal components)"
   }
  },
  { "title": "Installation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Kedify Installation Info",
   "type": "table",
   "description": "Per-component health and version reported by kedify_agent_component_up.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kedify_agent_component_up{name=~\"predictorAddon\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Component Status",
   "type": "table",
   "description": "Per-component health and version reported by kedify_agent_component_up.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "kedify_agent_component_up{name=~\"predictorAddon\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Runtime Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 11, "x": 3, "y": 28 },
   "targets": [
    { "expr": "kedify_predictor_runtime_info", "legendFormat": "Agent runtime" }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kedify Prediction Controller",
     "type": "logs",
     "gridPos": { "h": 21, "w": 12, "x": 0, "y": 178 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{service_name=~\"prediction-controller\"} |= ``"
      }
     ]
    },
    {
     "title": "Kedify Prophet",
     "type": "logs",
     "gridPos": { "h": 21, "w": 12, "x": 12, "y": 178 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{service_name=\"keda-prophet\"} |= ``"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "logs",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 263 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{service_name=~\"prediction-controller|keda-prophet\"} |= `` | detected_level = `error`"
      }
     ]
    }
   ]
  },
  { "title": "gRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "messages received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "keda_internal_metricsservice_grpc_client_msg_received_total",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "messages sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "keda_internal_metricsservice_grpc_client_msg_sent_total",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Response Latency for GetRawMetricsStream",
   "type": "bargauge",
   "description": "Histogram of response latency (seconds) of the gRPC until it is finished by the application.",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keda_internal_metricsservice_grpc_client_handling_seconds_bucket{grpc_method=\"GetRawMetricsStream\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response Latency for SubscribeMetric",
   "type": "bargauge",
   "description": "Histogram of response latency (seconds) of the gRPC until it is finished by the application.",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keda_internal_metricsservice_grpc_client_handling_seconds_bucket{grpc_method=\"SubscribeMetric\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response Latency CDF",
   "type": "bargauge",
   "description": "cumulative distribution function for latencies",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keda_internal_metricsservice_grpc_client_handling_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum(rate(keda_internal_metricsservice_grpc_client_handling_seconds_bucket[5m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}