{{- if and .Values.metricsServer.enabled .Values.rbac.create (eq .Values.kedify.multitenant.mode "default") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ (include "keda.operator.name" .) }}-metrics-server-kedify
    {{- include "keda.labels" . | indent 4 }}
  name: {{ (include "keda.operator.name" .) }}-metrics-server-kedify
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ (include "keda.operator.name" .) }}-metrics-server-kedify
    {{- include "keda.labels" . | indent 4 }}
  name: {{ (include "keda.operator.name" .) }}-metrics-server-kedify
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ (include "keda.operator.name" .) }}-metrics-server-kedify
subjects:
- kind: ServiceAccount
  name: {{ (.Values.serviceAccount.metricServer).name | default .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
