{{- if .Values.agent.createCrds }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crdInstall" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-4"
    {{- include "crdInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "crdInstall" . | quote }}
    role: {{ include "crdInstallSelector" . | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "crdInstall" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-3"
    {{- include "crdInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "crdInstall" . | quote }}
    role: {{ include "crdInstallSelector" . | quote }}
rules:
- apiGroups:
  - ""
  resources:
  # does this job really need to create jobs?
  - jobs
  verbs:
  - create
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - patch
#  can this be restricted to only the CRDs agent needs?
#  resourceNames:
#  - kedifyconfigurations.install.kedify.io
#  - scalingpolicies.keda.kedify.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "crdInstall" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-2"
    {{- include "crdInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "crdInstall" . | quote }}
    role: {{ include "crdInstallSelector" . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "crdInstall" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "crdInstall" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
