{{- if .Values.agent.createKedifyConfiguration }}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-default-kedifyconfig
  namespace: {{ .Release.Namespace }}
  labels:
    app: create-default-kedifyconfig
  {{- if not .Values.hookless }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded,hook-failed"
  {{- end }}
spec:
  ttlSecondsAfterFinished: 43200 # 12h
  backoffLimit: 2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: create-default-kedifyconfig
    spec:
      restartPolicy: Never
      serviceAccountName: install-crs
      {{- with .Values.agent.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: default-kedifyconfig
        configMap:
          name: default-kedifyconfig
          items:
          - key: content
            path: default-kedifyconfig.yaml
      initContainers:
      - name: wait-crds
        image: "{{ .Values.agent.kubectlImage.repository }}:{{ .Values.agent.kubectlImage.tag }}"
        imagePullPolicy: {{ .Values.agent.kubectlImage.pullPolicy }}
        command:
        - sh
        args:
        - -c
        - |
          echo "Waiting for CRD kedifyconfigurations.install.kedify.io to exist & register"
          while ! kubectl wait --for condition=established --timeout=300s crd/kedifyconfigurations.install.kedify.io 2> /dev/null; do sleep .5 && printf .; done
        {{- with .Values.agent.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      containers:
      - name: create-default-kedifyconfig
        image: "{{ .Values.agent.kubectlImage.repository }}:{{ .Values.agent.kubectlImage.tag }}"
        imagePullPolicy: {{ .Values.agent.kubectlImage.pullPolicy }}
        {{- with .Values.agent.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: default-kedifyconfig
          mountPath: /data/default-kedifyconfig.yaml
          subPath: default-kedifyconfig.yaml
        command:
        - sh
        args:
        - -c
        - |
          set -o nounset
          for i in $(seq 20)
          do
            kubectl apply -f /data/ 2>&1 && {
              _ok=1
              break
            }
            _sec=$(echo "1.5^$i" | bc)
            echo "Waiting ${_sec} seconds.."
            sleep ${_sec}
          done
          if [ -z "${_ok:-}" ]; then
            echo "Failed to apply default KedifyConfiguration after 20 attempts, exiting with error"
            exit 1
          fi

        {{- if .Values.hookless }}
          kubectl delete -n {{ .Release.Namespace }} cm/default-kedifyconfig --ignore-not-found || true
          echo "Deleting itself in 10 seconds..."
          sleep 10 && kubectl delete -n {{ .Release.Namespace }} --ignore-not-found \
            sa/install-crs \
            job/create-default-kedifyconfig \
            clusterrole/install-crs || true
        {{- end }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
