{{- if .Values.agent.createKedifyConfiguration }}
{{- if eq .Values.hooks "argo" }}
{{- $crOrig := (tpl ($.Files.Get "files/crs/default-kedifyconfig.yaml") $) | fromYaml }}
{{- $crPatch := dict "metadata" (dict "annotations" (dict "argocd.argoproj.io/sync-wave" "-4")) }}
{{ toYaml (deepCopy $crOrig | merge $crPatch) }}
{{- else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-kedifyconfig
  namespace: {{ .Release.Namespace }}
  {{- if eq .Values.hooks "helm" }}
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded,hook-failed"
    helm.sh/hook-weight: "0"
  {{- end }}
data:
  content: |
{{ tpl ($.Files.Get "files/crs/default-kedifyconfig.yaml") $ | indent 4 }}
{{- end }}
---
{{- end }}
