{{- if .Values.agent.rbac.create }}
{{- if .Values.agent.rbac.readLogs }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: can-read-logs
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kedify-agent-can-read-logs
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: can-read-logs
subjects:
- kind: ServiceAccount
  name: kedify-agent
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
