name: Helm Chart CI (Kedify Agent)

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-kedify-agent.yml'
      - 'kedify-agent/**'
  pull_request:
    branches:
      - main
      - release/*
    paths:
      - '.github/workflows/ci-kedify-agent.yml'
      - 'kedify-agent/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-and-render:
    name: Lint and render Kedify Agent
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4

      - name: Install Helm
        uses: Azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0

      - name: Add Kedify chart repository
        run: helm repo add kedify https://kedify.github.io/charts

      - name: Build chart dependencies
        run: helm dependency build kedify-agent

      - name: Lint chart
        run: helm lint kedify-agent --values kedify-agent/test/test-values.yaml

      - name: Test KPA rendering
        run: kedify-agent/test/kpa-rendering.sh
