name: Helm Publish (OCI)
on:
  workflow_dispatch:
    inputs:
      version:
        description: "the workflow will figure out the correct chart version (patch++) but optionally this can be overwritten here"
        required: false
        default: ''
        type: string
      chart:
        description: "select the chart you want to release"
        required: true
        type: choice
        options:
          - kedify-proxy
  workflow_call:
    inputs:
      version:
        description: "the workflow will figure out the correct chart version (patch++) but optionally this can be overwritten here"
        required: false
        default: ''
        type: string
      chart:
        description: "what chart you want to release: [kedify-proxy]"
        required: true
        type: string
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Smoke test helm chart 'renderability'
        run: |
          helm template ./${{ inputs.chart }}

  publish:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump the version if requested
        id: version
        run: |
          set -xeuo pipefail
          version=${{ inputs.version }}
          if [[ $version == "" ]]; then
            name=$(yq '.name' ${{ inputs.chart }}/Chart.yaml)
            last_version=$(yq '.version' ${{ inputs.chart }}/Chart.yaml)
            version=$(echo "$last_version" | awk  -F. '/[0-9]+\./{$NF++;print}' OFS=.
          fi
          echo "newVersion=${version}" >> ${GITHUB_OUTPUT}
          yq '.version = env(newVersion)' ${{ inputs.chart }}/Chart.yaml

      - name: Generate docs for helm chart - helmchart/otel-add-on/README.md
        uses: docker://jnorwood/helm-docs@sha256:7e562b49ab6b1dbc50c3da8f2dd6ffa8a5c6bba327b1c6335cc15ce29267979c
        with:
          args: |
            --template-files=${{ inputs.chart }}/_helm-docs-template.gotmpl --sort-values-order=file --chart-search-root=${{ inputs.chart }} --ignore-non-descriptions

      - name: Publish Helm chart
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: ${{ inputs.chart }}
          repository: kedify/charts
          tag: ${{ steps.version.outputs.newVersion }}
          path: ${{ inputs.chart }}
          registry: ghcr.io
          registry_username: kedify
          registry_password: ${{ secrets.PAT_TOKEN }}

      - name: Push the commit w/ version bump and docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: ${{ inputs.chart }}/Chart.yaml
          token: ${{ secrets.PAT_TOKEN }}

      - name: Push Tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          create_annotated_tag: true
          tag_prefix: ""
          custom_tag: ${{ inputs.chart }}-${{ steps.version.outputs.newVersion }}
