name: Helm Publish (OCI)
on:
  workflow_dispatch:
    inputs:
      version:
        description: "new version of the helm chart that should be released"
        required: false
        default: ''
        type: string
      chart:
        description: "select the chart you want to release"
        required: true
        type: choice
        options:
          - kedify-proxy
  workflow_call:
    inputs:
      version:
        description: "new version of the helm chart that should be released"
        required: false
        default: ''
        type: string
      chart:
        description: "what chart you want to release: [kedify-proxy]"
        required: true
        type: string
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Smoke test helm chart 'renderability'
        run: |
          helm template ./${{ inputs.chart }}

  publish:
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      # required by appany/helm-oci-chart-releaser so that the implicit secrets.GITHUB_TOKEN can be used for pushing the OCI artifact to ghcr.io registry
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Publish Helm chart
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: ${{ inputs.chart }}
          repository: kedify/charts
          tag: ${{ inputs.version }}
          path: ${{ inputs.chart }}
          registry: ghcr.io
          registry_username: kedify
          registry_password: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Summary
        run: |
          <<EOF>> ${GITHUB_STEP_SUMMARY} cat
          # Success :rocket:
          
          Helm chart \`${{ inputs.chart }}@${{ inputs.version }}\` has been published.
          
          Continue with:
          
          \`\`\`
          helm template oci://ghcr.io/kedify/charts/${{ inputs.chart }} --version=${{ inputs.version }}
          # or
          helm upgrade -i foo oci://ghcr.io/kedify/charts/${{ inputs.chart }} --version=${{ inputs.version }}
          # or
          crane ls ghcr.io/kedify/charts/${{ inputs.chart }} --full-ref
          \`\`\`

          OCI repo: https://github.com/kedify/charts/pkgs/container/charts%2F${{ inputs.chart }}/versions
          EOF
