name: Sync with upstream
on:
  schedule:
          # ┌───────────── minute (0 - 59)
          # │ ┌───────────── hour (0 - 23)
          # │ │ ┌───────────── day of the month (1 - 31)
          # │ │ │ ┌───────────── month (1 - 12)
          # │ │ │ │ ┌───────────── day of the week (0 - 6)
          # │ │ │ │ │                       
          # │ │ │ │ │
          # │ │ │ │ │
  - cron:  "* 7 * * *"
  workflow_dispatch:
    inputs:
      upstreamRepo:
        description: "Upstream Repo - Where we should get the changes from. If not specified, it's 'kedacore/charts'"
        default: "kedacore/charts"
        required: false
        type: string
      downstreamRepo:
        description: "Downstream Repo - To what repo we are syncying. If not specified, it's 'kedify/charts' (this repo)"
        default: "kedify/charts"
        required: false
        type: string

env:
  UPSTREAM_REPO: ${{ github.event.inputs.upstreamRepo || 'kedacore/charts' }}
  DOWNSTREAM_REPO: ${{ github.event.inputs.downstreamRepo || 'kedify/charts' }}

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0
      - run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "Kedify Bot"
          git remote add upstream https://github.com/${{ env.UPSTREAM_REPO }}.git
          git pull --rebase upstream main
      - name: Open Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          push-to-fork: ${{ env.DOWNSTREAM_REPO }}
          commit-message: Syncing upstream helm charts
          title: Syncing upstream helm charts
          body: |
            :package: Syncing upstream helm chart :package:

            ### Release?

            The sync mechanism doesn't deal with releases.

            This automated PR was created by [this action][1].

            [1]: https://github.com/kedify/charts/actions/runs/${{ github.run_id }}
          branch: upstream-sync
          delete-branch: true
          signoff: true

      - name: Check PR
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
