name: kedify-proxy milestones tracking with release

on:
  pull_request_target:
    types: [closed]
    paths:
      - kedify-proxy/**

jobs:
  milestone_tracker:
    if: github.event.pull_request.merged == true

    permissions:
      contents: write
      pull-requests: write
      issues: write
      packages: write

    uses: ./.github/workflows/milestones-tracker.yaml
    with:
      chart: kedify-proxy
      prNumber: ${{ github.event.pull_request.number }}
