name: http-add-on milestones tracking with release

on:
  pull_request:
    types: [closed]
    paths:
      - http-add-on/**

jobs:
  milestone_tracker:
    if: github.event.pull_request.merged == true
    secrets: inherit

    permissions:
      contents: write
      pull-requests: write

    uses: ./.github/workflows/milestones-tracker.yaml
    with:
      chart: http-add-on
      prNumber: ${{ github.event.pull_request.number }}
